import torch
from transformers import pipeline

# Load the question answering model
qa_model = pipeline("question-answering", model='distilbert-base-cased-distilled-squad')


# Function to interact with the model
def answer_question(context, question):
    # Generate an answer to the question
    answer = qa_model(question=question, context=context)
    return answer['answer']


if __name__ == "__main__":
    # Example context and question
    question = ''
    context = """
    Transformers (formerly known as pytorch-transformers and pytorch-pretrained-bert) provides general-purpose architectures (BERT, GPT-2, RoBERTa, XLM, DistilBert, XLNet…) for Natural Language Understanding (NLU) and Natural Language Generation (NLG) with over 32+ pretrained models in 100+ languages and deep interoperability between TensorFlow 2.0 and PyTorch.
    Species Name,
    Common name: Trout and salmon
    Common name: Pumpkinseed
    Common name: Yellow perch,"Scientific name: Perca flavescens (Perca means ""dusky""; flavescens means ""becoming gold-colored"")","Distribution: The yellow perch occurs in all three drainage basins in Wisconsin (Lake Michigan, Mississippi River, and Lake Superior), in all of the state's boundary waters, and in Lakes Michigan and Superior. Because the yellow perch is a glacial lakes species, it is widely distributed except in the unglaciated region of southwestern Wisconsin.","Spawning: Spawning normally occurs shortly after ice-out in April or early May at water temperatures of 45 - 52� F. Yellow perch spawning closely follows that of walleyes and often coincides with that of suckers. Yellow perch are random spawners, and do not construct nests, nor do they guard their eggs and their young.","Angling: Yellow perch are primarily bottom feeders with a slow deliberate bite. They eat almost anything but prefer minnows, insect larvae, plankton, and worms. Tackle may range from a simple handline or a fly rod in summer to a short, whippy, jigging rod in winter. Because perch prefer cooler water, the best fishing is usually in deep water. Perch move about in schools, often numbering in the hundreds. If one spot is unproductive after a few tries, it is best to move to other spots until a school is located."
    Common name: Walleye,"Scientific name: Sander vitreus (Sander refers to the German common name of the European relative) and vitreus means ""glassy"", referring to the large eye.",Distribution: It is believed that the walleye was originally confined to the larger lakes and waterways in Wisconsin. The extensive stocking of walleye fry and fingerlings that occurred early in many Wisconsin waters partly obscured the original distribution of the species. Today the walleye is present throughout Wisconsin.,"Spawning: The spawning migration of walleye begins soon after the ice goes out, at water temperatures of 38 - 44� F. Spawning in Wisconsin generally occurs between mid-April and early May, although it may extend from the beginning of April to the middle of May. Walleye spawning ordinarily reaches a peak when water temperatures are 42 - 50� F. The walleye is not a territorial fish at spawning time; they usually broadcast their eggs and exercise no parental care.","Angling: The walleye is one of the most highly prized game fishes in Wisconsin. Thousands are caught each year during their spring spawning runs. Walleyes are primarily minnow feeders, but leeches, small bullheads, nightcrawlers, and various small plugs are favorite baits. In clear waters, walleyes usually stay in deeper areas during the day, moving into the shallows at night. In more turbid waters, they can be caught throughout the day. The large, unusual eyes of the walleye are designed to help them easily find their prey."
    Scientific name: Esox lucius (Esox comes from the old name for pike in Europe and lucius comes from the supposed Latin name for the species).,"Distribution: In Wisconsin, the northern pike occurs in the Mississippi River, Lake Michigan, and Lake Superior drainage basins. It is widely distributed throughout the state except in the unglaciated area, where it is sparsely dispersed except in large river systems and impounded areas. The northern pike is generally common except in the southeastern quarter of the state, where populations are seriously depressed.","Spawning: Spawning may occur from late March to early April, as soon as the ice begins to break up in the spring. Migrations into the spawning areas take place during the night. Spawning occurs at temperatures between 34 and 40� F, but 36 - 37� F seems to be the preferred range. Spawning takes place in flooded areas with emergent vegetation and involves one female and from one to three attendant males. Eggs are deposited on vegetation to which they adhere. There is no parental care.","Angling: Unlike other common species of game fish, northern pike are most active when the water is cool. The northern pike is quite accommodating to anglers, biting best during the daylight hours. Being a predator, northerns prefer live fish baits and wobbling spoons. They are a favorite target of ice fishermen with tip-ups."
    Common name: Bullheads (Brown, Yellow and Black)
    Common name: Muskellunge (Musky),"Scientific name: Esox masquinongy (Esox comes from the old name for pike in Europe and masquinongy comes from the Cree ""mashk"" meaning deformed and ""kinonge"" is a pike.","Distribution: The muskellunge occurs in all three drainage basins in Wisconsin (Lake Michigan, Mississippi River, and Lake Superior) but is most widely distributed in the Chippewa, Flambeau, St. Croix, Black, and Wisconsin rivers of the Mississippi basin. Its presence in central and southern Wisconsin is the result of widespread stocking of fry and fingerlings.","Spawning: Within the north and south limits of the Wisconsin muskellunge range, spawning occurs from mid-April to mid-May, with the peak occurring early in the season. Optimum spawning temperature is about 55� F, but may range from 49 - 60� F. Eggs are usually deposited indiscriminately over several hundred yards of shoreline. There is no parental care. Adult spawners return to the same spawning ground in consecutive years.","Angling: The natural home for the musky is in the northern lakes and rivers. It is a solitary fish and lurks in weed beds or other protective cover. Anglers usually have the best luck fishing during the daytime. Large plugs, spoons, and bucktails are the best artificial baits. A live fish bait 10-12 inches long is also good.",Managing Wisconsin's state fish
    Common name: Lake (or rock) sturgeon
    Common name: Channel and Flathead catfish,Channel and Flathead catfish distribution in Wisconsin�[PDF],Catfish fact sheet [PDF],The Purrfect choice [PDF]
    Common name: Bluegill,"Scientific name: Lepomis macrochirus (Lepomis means ""scaled cheek""; macrochirus means ""large hand"", possibly in reference to the size of the pectoral fin).","Distribution: Bluegill occurs in all three drainage basins in Wisconsin (Lake Michigan, Mississippi River, and Lake Superior). Originally it was not present in the Lake Superior basin, but as a result of widespread stocking, it is now present and reproducing in many lakes and rivers.","Spawning: Spawning takes place from late May to early August (peaking in June) at water temperatures between 67 - 80� F. Males select a sand or gravel bar that can be hollowed out to form a nest. Before and after spawning, the male bluegill defends the nest against all species, but most vigorously against other male sunfishes.","Angling: Plain garden worms are the favorite bait for bluegills, but they can be caught on a number of different types of lures. The fly fisher can have fun with poppers, especially in spring and early summer, when nests are concentrated in shallow water. Most large bluegills are taken in deep water during the summer months by drifting with the wind using worms. Wintertime jigging in the weed beds with grubs or mousies on ice jigs also produces excellent results."
    Common name: Black crappie,"Scientific name: Pomoxis nigromaculatus (Pomoxis means ""sharp opercle (cheek)""; nigromaculatus means ""black spotted"")","Distribution: The black crappie occurs in all three drainage basins in Wisconsin (Lake Michigan, Mississippi River, and Lake Superior). This glacial species is well distributed throughout the state, except in the streams of the driftless area of southwestern Wisconsin.","Spawning:  In Wisconsin, the black crappie usually spawns in May and June; however, during a colder season, spawning may be delayed until July. Favorable spawning temperatures range from 64 to 68� F. The male sweeps out a nest in the sand or fine gravel and guards the nest and defends the young until they start to feed.","Angling: The black crappie is considered an excellent game fish when taken on light tackle. Extreme care must be taken in landing these fish because their mouths are very tender. Anglers specializing in catching black crappie know that to be successful the bait must be kept constantly moving. The best baits are small minnows, small maribou-covered jigs, plastic minnows, or small streamer flies cast along the outer edges of weed beds. The crappie lies in weed beds in deep water during the day and bites best in the early morning or toward evening. In summer, with the abundance of small fish for feed, they are more difficult to catch. Small minnows are used as bait in winter."
    Micropterus salmoides (Micropterus means ""small fin""; salmoides means ""trout-like"" in gameness and food).","The largemouth bass occurs in all three drainage basins in Wisconsin (Lake Michigan, Mississippi River, and Lake Superior); it is least widespread in the driftless area of southwestern Wisconsin. Wisconsin is near the northern limit of distribution, and it has been suggested that its presence in the state, especially in the northern counties, resulted from introductions.","The spawning of largemouth bass in Wisconsin occurs from late April to early July. The selection of nest sites begin when water temperatures reach 60� F, and eggs are laid when the water temperatures are at 62 - 65� F. The male largemouth bass usually selects a sand or gravel bottom upon which to build a nest; however, the fish will also nest on soft bottoms, where they are able to expose such hard objects as roots, twigs, and snail shells on which to deposit the eggs. Territorial defense against intruders is practiced by the largemouth bass as it is by other sunfishes.","Largemouth bass will bite on almost anything. They can be caught on minnows, worms, or other live bait, plus poppers or streamers presented with a fly rod, or plugs thrown from a casting or spinning rod. Because the bass is usually associated with weeds, a weedless bait will often be necessary. Best fishing times are early morning and evening during the warm months. Bass like warm water and warm weather. Few bite in the winter."
    """
    while question != "q":
        question = input("Enter you question here:")

    # Get the answer
        answer = answer_question(context, question)

        print("Answer:", answer)